language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

jobs:
  include:
    - stage: build
      script: mvn compile -DskipTests=true -B
    - stage: test
      script: mvn test -B