language: java

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk11

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script: mvn compile -DskipTests=true -B
    - stage: test
      script: mvn test -B