name: build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          #settings-path: ${{ github.workspace }} # location for the settings.xml
          #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Build with Maven
        run: ./mvnw install
